package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/UTXOnly/agent_of_chaos/internal/ddapi"
	"github.com/UTXOnly/agent_of_chaos/internal/gen"
	"github.com/UTXOnly/agent_of_chaos/internal/notebook"
	"github.com/UTXOnly/agent_of_chaos/internal/report"
)

func init() {
	register(command{name: "run", short: "run one experiment end to end (compose up → measure → report → down)", run: runRun})
	register(command{name: "profiles", short: "list experiment profiles in ./profiles", run: runProfiles})
}

// Profile is an experiment definition; see profiles/README.md.
type Profile struct {
	Name        string                    `yaml:"name"`
	Description string                    `yaml:"description"`
	Duration    gen.Duration              `yaml:"duration"`
	Warmup      gen.Duration              `yaml:"warmup"`
	Drain       gen.Duration              `yaml:"drain"`
	Agent       ProfileAgent              `yaml:"agent"`
	Generators  map[string]map[string]any `yaml:"generators"`
	Faults      []FaultStep               `yaml:"faults"`
	Compose     []string                  `yaml:"compose"` // extra compose files
	Notes       []string                  `yaml:"notes"`
}

type ProfileAgent struct {
	Image string            `yaml:"image"`
	Env   map[string]string `yaml:"env"`
}

type FaultStep struct {
	At    gen.Duration   `yaml:"at"`
	Set   map[string]any `yaml:"set"`
	Clear bool           `yaml:"clear"`
}

func loadProfile(path string) (*Profile, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var p Profile
	if err := yaml.Unmarshal(b, &p); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	if p.Name == "" {
		p.Name = strings.TrimSuffix(filepath.Base(path), filepath.Ext(path))
	}
	if p.Duration <= 0 {
		return nil, fmt.Errorf("%s: duration must be set", path)
	}
	if p.Drain <= 0 {
		p.Drain = gen.Duration(45 * time.Second)
	}
	return &p, nil
}

// envKey turns a profile key into a generator env var: "rotate-bytes" →
// AOC_ROTATE_BYTES; keys already prefixed are kept.
func envKey(k string) string {
	if strings.HasPrefix(k, "AOC_") || strings.HasPrefix(k, "DD_") {
		return k
	}
	return EnvPrefix + strings.ToUpper(strings.ReplaceAll(k, "-", "_"))
}

func yamlScalar(v any) string {
	switch x := v.(type) {
	case string:
		return x
	case bool:
		if x {
			return "true"
		}
		return "false"
	case int, int64, float64:
		return fmt.Sprint(x)
	default:
		return fmt.Sprint(v)
	}
}

// overrideCompose renders the compose override that applies the profile.
func overrideCompose(p *Profile, agentImage string) (string, []string) {
	var b strings.Builder
	b.WriteString("# generated by aoc run — do not edit\nservices:\n")
	if agentImage != "" || len(p.Agent.Env) > 0 {
		b.WriteString("  datadog-agent:\n")
		if agentImage != "" {
			fmt.Fprintf(&b, "    image: %q\n", agentImage)
		}
		if len(p.Agent.Env) > 0 {
			b.WriteString("    environment:\n")
			for _, k := range sortedStringKeys(p.Agent.Env) {
				fmt.Fprintf(&b, "      %s: %q\n", k, p.Agent.Env[k])
			}
		}
	}
	var enabled []string
	names := make([]string, 0, len(p.Generators))
	for n := range p.Generators {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		spec := p.Generators[n]
		if e, ok := spec["enabled"]; ok && !truthy(e) {
			continue
		}
		enabled = append(enabled, n)
		env := map[string]string{}
		for k, v := range spec {
			if k == "enabled" || k == "scale" {
				continue
			}
			env[envKey(k)] = yamlScalar(v)
		}
		if len(env) == 0 {
			continue
		}
		fmt.Fprintf(&b, "  %s:\n    environment:\n", n)
		for _, k := range sortedStringKeys(env) {
			fmt.Fprintf(&b, "      %s: %q\n", k, env[k])
		}
	}
	return b.String(), enabled
}

func truthy(v any) bool {
	switch x := v.(type) {
	case bool:
		return x
	case string:
		return x == "true" || x == "yes" || x == "1"
	}
	return true
}

func sortedStringKeys(m map[string]string) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return ks
}

// compose wraps `docker compose -f … ` invocations.
type compose struct {
	cmd   []string
	files []string
	env   []string
	dir   string
	log   func(string, ...any)
}

func (c *compose) args(extra ...string) []string {
	var a []string
	a = append(a, c.cmd[1:]...)
	for _, f := range c.files {
		a = append(a, "-f", f)
	}
	return append(a, extra...)
}

func (c *compose) run(ctx context.Context, extra ...string) error {
	cmd := exec.CommandContext(ctx, c.cmd[0], c.args(extra...)...)
	cmd.Dir = c.dir
	cmd.Env = append(os.Environ(), c.env...)
	cmd.Stdout, cmd.Stderr = os.Stderr, os.Stderr
	c.log("$ %s %s", c.cmd[0], strings.Join(c.args(extra...), " "))
	return cmd.Run()
}

func (c *compose) output(ctx context.Context, extra ...string) ([]byte, error) {
	cmd := exec.CommandContext(ctx, c.cmd[0], c.args(extra...)...)
	cmd.Dir = c.dir
	cmd.Env = append(os.Environ(), c.env...)
	var out, errb bytes.Buffer
	cmd.Stdout, cmd.Stderr = &out, &errb
	err := cmd.Run()
	if err != nil {
		return out.Bytes(), fmt.Errorf("%v: %s", err, strings.TrimSpace(errb.String()))
	}
	return out.Bytes(), nil
}

func runProfiles(args []string) int {
	dir := "profiles"
	if len(args) > 0 && args[0] != "-h" && args[0] != "--help" {
		dir = args[0]
	}
	matches, _ := filepath.Glob(filepath.Join(dir, "*.yaml"))
	if len(matches) == 0 {
		return fail("no profiles in %s (run from the repo root, or pass a directory)", dir)
	}
	fmt.Printf("\nProfiles in %s (aoc run --profile PATH):\n\n", dir)
	for _, m := range matches {
		p, err := loadProfile(m)
		if err != nil {
			fmt.Printf("  %-28s (invalid: %v)\n", m, err)
			continue
		}
		var gens []string
		for _, n := range sortedGenNames(p) {
			if e, ok := p.Generators[n]["enabled"]; ok && !truthy(e) {
				continue
			}
			gens = append(gens, n)
		}
		fmt.Printf("  %-28s %s\n", m, wrap(p.Description, 90, 31))
		fmt.Printf("  %-28s duration=%s warmup=%s drain=%s generators=%s faults=%d\n\n", "", p.Duration, p.Warmup, p.Drain, strings.Join(gens, ","), len(p.Faults))
	}
	return 0
}

func sortedGenNames(p *Profile) []string {
	names := make([]string, 0, len(p.Generators))
	for n := range p.Generators {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

func wrap(s string, width, indent int) string {
	words := strings.Fields(s)
	var lines []string
	var cur string
	for _, w := range words {
		if len(cur)+len(w)+1 > width && cur != "" {
			lines = append(lines, cur)
			cur = w
			continue
		}
		if cur == "" {
			cur = w
		} else {
			cur += " " + w
		}
	}
	if cur != "" {
		lines = append(lines, cur)
	}
	return strings.Join(lines, "\n"+strings.Repeat(" ", indent))
}

func runRun(args []string) int {
	fs := newFlagSet("run",
		"Run one experiment end to end with docker compose: start the intake and\n"+
			"the agent, wait for the agent to be healthy, start the generators, open\n"+
			"a measured window after a warm-up, apply the profile's fault timeline,\n"+
			"stop the generators, drain, then write report.json/report.md/timeseries.csv\n"+
			"plus the agent's status and logs into the results directory.",
		"  aoc run --profile profiles/baseline.yaml --name baseline\n"+
			"  aoc run --profile profiles/baseline.yaml --agent-image datadog/agent-dev:my-build --name candidate\n"+
			"  aoc compare results/baseline results/candidate")
	profilePath := fs.Str("profile", "", "experiment profile (YAML), see profiles/README.md")
	name := fs.Str("name", "", "run name → results/<name> (default: profile name)")
	agentImage := fs.Str("agent-image", "", "agent image under test (overrides the profile and DD_AGENT_IMAGE)")
	duration := fs.Duration("duration", 0, "override the profile's measured window")
	composeFile := fs.Str("compose-file", "docker-compose.yml", "base compose file")
	composeCmd := fs.Str("compose-cmd", "docker compose", "compose command")
	intake := fs.Str("intake", "http://localhost:8282", "how this machine reaches the intake")
	out := fs.Str("out", "results", "results root directory")
	keep := fs.Bool("keep", false, "leave the stack running afterwards (default: docker compose down -v)")
	noBuild := fs.Bool("no-build", false, "do not rebuild the aoc image")
	mkNotebook := fs.Bool("notebook", os.Getenv("DD_APP_KEY") != "", "create a Datadog notebook for the run (default: when DD_APP_KEY is set; notebook.json is always written)")
	ddSite := fs.Str("dd-site", envOr("DD_SITE", "datadoghq.com"), "Datadog site for the notebook (env DD_SITE)")
	if !fs.parse(args) {
		return 2
	}
	if *profilePath == "" {
		return fail("run: --profile is required (see aoc profiles)")
	}
	p, err := loadProfile(*profilePath)
	if err != nil {
		return fail("run: %v", err)
	}
	if *name == "" {
		*name = p.Name
	}
	if *duration > 0 {
		p.Duration = gen.Duration(*duration)
	}
	img := *agentImage
	if img == "" {
		img = p.Agent.Image
	}
	if img == "" {
		img = os.Getenv("DD_AGENT_IMAGE")
	}
	resultsDir := filepath.Join(*out, sanitize(*name))
	if err := os.MkdirAll(resultsDir, 0o755); err != nil {
		return fail("run: %v", err)
	}
	logf := func(format string, a ...any) {
		fmt.Fprintf(os.Stderr, "  %s  %s\n", time.Now().Format("15:04:05"), fmt.Sprintf(format, a...))
	}

	override, enabled := overrideCompose(p, img)
	overridePath := filepath.Join(resultsDir, "compose.override.yml")
	if err := os.WriteFile(overridePath, []byte(override), 0o644); err != nil {
		return fail("run: %v", err)
	}
	if src, err := os.ReadFile(*profilePath); err == nil {
		os.WriteFile(filepath.Join(resultsDir, "profile.yaml"), src, 0o644)
	}
	if len(enabled) == 0 {
		return fail("run: profile enables no generators")
	}

	c := &compose{cmd: strings.Fields(*composeCmd), files: append([]string{*composeFile}, p.Compose...), dir: ".", log: logf}
	c.files = append(c.files, overridePath)
	c.env = []string{"AOC_RUN_NAME=" + *name}
	if img != "" {
		c.env = append(c.env, "DD_AGENT_IMAGE="+img)
	}

	ctx, cancel := signalContext()
	defer cancel()
	fmt.Fprintf(os.Stderr, "\naoc run  %s  profile=%s  agent=%s  window=%s  warmup=%s  drain=%s\n  %s\n\n",
		*name, *profilePath, orDefault(img, "compose default"), p.Duration, p.Warmup, p.Drain, p.Description)

	// Clean slate: old log files/offsets would pollute the ledgers.
	c.run(ctx, "down", "-v", "--remove-orphans")
	upArgs := []string{"up", "-d"}
	if !*noBuild {
		upArgs = append(upArgs, "--build")
	}
	if err := c.run(ctx, append(upArgs, "intake", "datadog-agent")...); err != nil {
		return fail("run: compose up: %v", err)
	}
	if err := waitHTTP(ctx, *intake+"/healthz", 60*time.Second); err != nil {
		return fail("run: intake not reachable at %s: %v", *intake, err)
	}
	logf("intake is up at %s", *intake)
	if err := waitAgent(ctx, c, 180*time.Second, logf); err != nil {
		return fail("run: %v", err)
	}

	if err := c.run(ctx, append([]string{"up", "-d", "--no-build"}, enabled...)...); err != nil {
		return fail("run: compose up generators: %v", err)
	}
	logf("generators started: %s", strings.Join(enabled, ", "))
	if err := waitGenerators(ctx, *intake, len(enabled), 60*time.Second, logf); err != nil {
		logf("warning: %v", err)
	}
	if p.Warmup > 0 {
		logf("warm-up %s", p.Warmup)
		if !sleepCtx(ctx, p.Warmup.D()) {
			return interrupted(c, *keep)
		}
	}

	// Open the measured window.
	if _, err := http.Post(*intake+"/harness/reset?name="+sanitize(*name), "", nil); err != nil {
		return fail("run: reset: %v", err)
	}
	windowStart := time.Now()
	logf("measured window open for %s (metrics tagged run:%s)", p.Duration, sanitize(*name))

	// Fault timeline, cut off at the end of the window.
	windowCtx, cancelWindow := context.WithDeadline(ctx, windowStart.Add(p.Duration.D()))
	defer cancelWindow()
	faultsDone := make(chan struct{})
	go func() {
		defer close(faultsDone)
		steps := append([]FaultStep(nil), p.Faults...)
		sort.SliceStable(steps, func(i, j int) bool { return steps[i].At < steps[j].At })
		for _, st := range steps {
			if st.At.D() >= p.Duration.D() {
				logf("fault step at t+%s is beyond the %s window; skipped", st.At, p.Duration)
				continue
			}
			if !sleepCtx(windowCtx, time.Until(windowStart.Add(st.At.D()))) {
				return
			}
			if st.Clear {
				req, _ := http.NewRequest("DELETE", *intake+"/harness/faults", nil)
				if resp, err := http.DefaultClient.Do(req); err == nil {
					resp.Body.Close()
					logf("faults cleared (t+%s)", st.At)
				}
				continue
			}
			body, _ := json.Marshal(st.Set)
			if resp, err := http.Post(*intake+"/harness/faults", "application/json", bytes.NewReader(body)); err == nil {
				resp.Body.Close()
				logf("faults set (t+%s): %s", st.At, string(body))
			}
		}
	}()

	if !sleepCtx(ctx, time.Until(windowStart.Add(p.Duration.D()))) {
		return interrupted(c, *keep)
	}
	<-faultsDone
	// Make sure no fault outlives the window, so the drain is clean.
	if req, err := http.NewRequest("DELETE", *intake+"/harness/faults", nil); err == nil {
		if resp, err := http.DefaultClient.Do(req); err == nil {
			resp.Body.Close()
		}
	}

	logf("window closed — stopping generators")
	mark(*intake, "measurement window closed")
	c.run(ctx, append([]string{"stop"}, enabled...)...)
	mark(*intake, "generators stopped, draining")
	hadFaults := len(p.Faults) > 0
	if hadFaults {
		logf("draining for the full %s (faults were injected: the agent's retry backoff can be long)", p.Drain)
	} else {
		logf("draining for up to %s (until everything arrived or the intake goes quiet)", p.Drain)
	}
	drainUntilQuiet(ctx, *intake, p.Drain.D(), hadFaults, logf)
	mark(*intake, "drain finished")

	// Collect.
	r, err := fetchReportFor(*intake, sanitize(*name))
	if err != nil {
		return fail("run: %v", err)
	}
	if hadFaults && r.Delivery.Missing > 0 {
		r.Notes = append(r.Notes, fmt.Sprintf("%s records were still missing when the %s drain ended. Faults were injected during the window and the agent retries with exponential backoff (up to minutes), so these may still have been buffered in the agent rather than lost; use a longer `drain` to tell the two apart.", fmtInt(r.Delivery.Missing), p.Drain))
	}
	raw, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return fail("run: %v", err)
	}
	csv, _ := fetchTimeseriesCSV(*intake, r.WindowStart.Unix())
	if err := writeReportFiles(resultsDir, r, raw, csv); err != nil {
		return fail("run: %v", err)
	}
	if outb, err := c.output(ctx, "exec", "-T", "datadog-agent", "agent", "status"); err == nil {
		os.WriteFile(filepath.Join(resultsDir, "agent-status.txt"), outb, 0o644)
	} else {
		logf("agent status unavailable: %v", err)
	}
	if outb, err := c.output(ctx, "logs", "--no-color", "--no-log-prefix", "--tail", "5000", "datadog-agent"); err == nil {
		os.WriteFile(filepath.Join(resultsDir, "agent.log"), outb, 0o644)
	}
	if outb, err := c.output(ctx, "logs", "--no-color", "--tail", "2000", "intake"); err == nil {
		os.WriteFile(filepath.Join(resultsDir, "intake.log"), outb, 0o644)
	}
	for _, g := range enabled {
		if outb, err := c.output(ctx, "logs", "--no-color", "--no-log-prefix", "--tail", "500", g); err == nil {
			os.WriteFile(filepath.Join(resultsDir, g+".log"), outb, 0o644)
		}
	}

	if !*keep {
		c.run(context.Background(), "down", "-v", "--remove-orphans")
	} else {
		logf("stack left running (--keep); intake at %s", *intake)
	}
	nbRes, nbErr := makeNotebook(context.Background(), []*report.Report{r}, notebook.Options{Site: *ddSite, AppURL: ddapi.AppURLFromEnv()}, filepath.Join(resultsDir, "notebook.json"), ddapi.FromEnv(), !*mkNotebook)
	fmt.Fprintf(os.Stderr, "\nresults in %s (report.md, report.json, timeseries.csv, notebook.json, agent-status.txt, agent.log)\n\n", resultsDir)
	printVerdict(r)
	switch {
	case nbErr != nil:
		fmt.Fprintf(os.Stderr, "notebook: %v\n", nbErr)
	case nbRes.URL != "":
		fmt.Printf("notebook: %s\n", nbRes.URL)
	case *mkNotebook:
		fmt.Printf("notebook: DD_APP_KEY not set — wrote %s; create it with `aoc notebook --results %s` or the Datadog MCP\n", nbRes.File, resultsDir)
	}
	if r.Delivery.Missing > 0 || r.Delivery.Duplicates > 0 {
		return 3
	}
	return 0
}

// mark posts an annotation event through the intake (a no-op without Datadog).
func mark(intake, text string) {
	if resp, err := http.Post(intake+"/harness/mark?text="+url.QueryEscape(text), "", nil); err == nil {
		resp.Body.Close()
	}
}

func orDefault(s, d string) string {
	if s == "" {
		return d
	}
	return s
}

func interrupted(c *compose, keep bool) int {
	fmt.Fprintln(os.Stderr, "\naoc: interrupted")
	if !keep {
		c.run(context.Background(), "down", "-v", "--remove-orphans")
	}
	return 130
}

func sleepCtx(ctx context.Context, d time.Duration) bool {
	if d <= 0 {
		return ctx.Err() == nil
	}
	select {
	case <-ctx.Done():
		return false
	case <-time.After(d):
		return true
	}
}

func waitHTTP(ctx context.Context, url string, timeout time.Duration) error {
	deadline := time.Now().Add(timeout)
	client := &http.Client{Timeout: 2 * time.Second}
	for {
		resp, err := client.Get(url)
		if err == nil {
			resp.Body.Close()
			if resp.StatusCode < 400 {
				return nil
			}
		}
		if time.Now().After(deadline) {
			if err == nil {
				return fmt.Errorf("HTTP %d", resp.StatusCode)
			}
			return err
		}
		if !sleepCtx(ctx, time.Second) {
			return ctx.Err()
		}
	}
}

// waitAgent polls `agent health` inside the container.
func waitAgent(ctx context.Context, c *compose, timeout time.Duration, logf func(string, ...any)) error {
	deadline := time.Now().Add(timeout)
	logf("waiting for the agent to report healthy")
	var lastErr error
	for time.Now().Before(deadline) {
		out, err := c.output(ctx, "exec", "-T", "datadog-agent", "agent", "health")
		if err == nil {
			logf("agent healthy")
			return nil
		}
		lastErr = fmt.Errorf("%v %s", err, strings.TrimSpace(string(out)))
		if !sleepCtx(ctx, 3*time.Second) {
			return ctx.Err()
		}
	}
	return fmt.Errorf("agent did not become healthy within %s: %v", timeout, lastErr)
}

type intakeStatus struct {
	Generators []struct {
		Name  string `json:"name"`
		Final bool   `json:"final"`
	} `json:"generators"`
	RecentLogsPerSec float64 `json:"recent_logs_per_sec"`
	Missing          int64   `json:"missing"`
}

func getStats(url string) (*intakeStatus, error) {
	resp, err := (&http.Client{Timeout: 10 * time.Second}).Get(url + "/harness/status")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	var s intakeStatus
	if err := json.NewDecoder(resp.Body).Decode(&s); err != nil {
		return nil, err
	}
	return &s, nil
}

func waitGenerators(ctx context.Context, url string, n int, timeout time.Duration, logf func(string, ...any)) error {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		if s, err := getStats(url); err == nil && len(s.Generators) >= n {
			logf("%d generator(s) reporting to the intake", len(s.Generators))
			return nil
		}
		if !sleepCtx(ctx, time.Second) {
			return ctx.Err()
		}
	}
	return fmt.Errorf("only some generators registered within %s — check `docker compose logs gen-plain`", timeout)
}

// drainUntilQuiet waits for every generator's final report and for missing
// to reach zero, bounded by max. Without faults it also stops once the
// intake has been quiet for 10 s; after faults the agent may be sleeping in
// its retry backoff, so only the full drain counts.
func drainUntilQuiet(ctx context.Context, url string, max time.Duration, hadFaults bool, logf func(string, ...any)) {
	deadline := time.Now().Add(max)
	quiet := 0
	for time.Now().Before(deadline) {
		if !sleepCtx(ctx, time.Second) {
			return
		}
		s, err := getStats(url)
		if err != nil {
			continue
		}
		allFinal := len(s.Generators) > 0
		for _, g := range s.Generators {
			if !g.Final {
				allFinal = false
			}
		}
		if allFinal && s.Missing == 0 {
			logf("drained: everything delivered")
			return
		}
		if s.RecentLogsPerSec == 0 {
			quiet++
		} else {
			quiet = 0
		}
		if allFinal && quiet >= 10 && !hadFaults {
			logf("drained: intake quiet for 10 s, %d record(s) still missing", s.Missing)
			return
		}
	}
	logf("drain ended after %s", max)
}
