package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/UTXOnly/agent_of_chaos/internal/ddapi"
	"github.com/UTXOnly/agent_of_chaos/internal/gen"
	"github.com/UTXOnly/agent_of_chaos/internal/intake"
	"github.com/UTXOnly/agent_of_chaos/internal/notebook"
	"github.com/UTXOnly/agent_of_chaos/internal/prof"
	"github.com/UTXOnly/agent_of_chaos/internal/report"
)

func init() {
	register(command{name: "run", short: "run one experiment end to end (compose up → measure → report → down)", run: runRun})
	register(command{name: "profiles", short: "list experiment profiles in ./profiles", run: runProfiles})
}

// Profile is an experiment definition; see profiles/README.md.
type Profile struct {
	Name        string                    `yaml:"name"`
	Description string                    `yaml:"description"`
	Duration    gen.Duration              `yaml:"duration"`
	Warmup      gen.Duration              `yaml:"warmup"`
	Drain       gen.Duration              `yaml:"drain"`
	Agent       ProfileAgent              `yaml:"agent"`
	Generators  map[string]map[string]any `yaml:"generators"`
	Faults      []FaultStep               `yaml:"faults"`
	Compose     []string                  `yaml:"compose"` // extra compose files
	Notes       []string                  `yaml:"notes"`
}

type ProfileAgent struct {
	Image string            `yaml:"image"`
	Env   map[string]string `yaml:"env"`
}

type FaultStep struct {
	At    gen.Duration   `yaml:"at"`
	Set   map[string]any `yaml:"set"`
	Clear bool           `yaml:"clear"`
}

// parseFaults turns --fault K=V values into the intake's fault fields
// (latency_ms=300, drop_rate=0.05, outage=true), rejecting unknown fields
// and out-of-range values before anything starts.
func parseFaults(list []string) (map[string]any, error) {
	kv, err := parseKV(list)
	if err != nil || len(kv) == 0 {
		return nil, err
	}
	set := make(map[string]any, len(kv))
	for k, v := range kv {
		var val any
		if json.Unmarshal([]byte(v), &val) != nil {
			val = v // free text, e.g. note=…
		}
		set[k] = val
	}
	return set, checkFaults(set)
}

func checkFaults(set map[string]any) error {
	body, _ := json.Marshal(set)
	dec := json.NewDecoder(bytes.NewReader(body))
	dec.DisallowUnknownFields()
	var f intake.Faults
	if err := dec.Decode(&f); err != nil {
		return fmt.Errorf("%v (fields: latency_ms, jitter_ms, error_rate, error_status, drop_rate, outage, read_bps, note)", err)
	}
	return f.Validate()
}

// describeFaults is the one-line summary of a --fault set.
func describeFaults(set map[string]any) string {
	body, _ := json.Marshal(set)
	var f intake.Faults
	_ = json.Unmarshal(body, &f)
	return f.String()
}

func loadProfile(path string) (*Profile, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	p, err := parseProfile(b, strings.TrimSuffix(filepath.Base(path), filepath.Ext(path)))
	if err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return p, nil
}

// parseProfile decodes a profile; name is used when the profile has none.
func parseProfile(b []byte, name string) (*Profile, error) {
	var p Profile
	if err := yaml.Unmarshal(b, &p); err != nil {
		return nil, err
	}
	if p.Name == "" {
		p.Name = name
	}
	if p.Duration <= 0 {
		return nil, errors.New("duration must be set")
	}
	if p.Drain <= 0 {
		p.Drain = gen.Duration(45 * time.Second)
	}
	return &p, nil
}

// enabledGenerators lists the compose services the profile turns on.
func (p *Profile) enabledGenerators() []string {
	var out []string
	for _, n := range sortedGenNames(p) {
		if e, ok := p.Generators[n]["enabled"]; ok && !truthy(e) {
			continue
		}
		out = append(out, n)
	}
	return out
}

// envKey turns a profile key into a generator env var: "rotate-bytes" →
// AOC_ROTATE_BYTES; keys already prefixed are kept.
func envKey(k string) string {
	if strings.HasPrefix(k, "AOC_") || strings.HasPrefix(k, "DD_") {
		return k
	}
	return EnvPrefix + strings.ToUpper(strings.ReplaceAll(k, "-", "_"))
}

func yamlScalar(v any) string {
	switch x := v.(type) {
	case string:
		return x
	case bool:
		if x {
			return "true"
		}
		return "false"
	case int, int64, float64:
		return fmt.Sprint(x)
	default:
		return fmt.Sprint(v)
	}
}

// agentSpec is the agent container of one run: the image, how to get it,
// and settings on top of the profile's.
type agentSpec struct {
	Image string
	Pull  string // compose pull_policy: always | missing | never (empty = compose default)
	Env   map[string]string
}

// overrideCompose renders the compose override that applies the profile and
// the agent spec. The agent's env is the profile's with the spec's on top.
func overrideCompose(p *Profile, agent agentSpec) (string, []string) {
	var b strings.Builder
	b.WriteString("# generated by aoc run — do not edit\nservices:\n")
	env := map[string]string{}
	for k, v := range p.Agent.Env {
		env[k] = v
	}
	for k, v := range agent.Env {
		env[k] = v
	}
	if agent.Image != "" || agent.Pull != "" || len(env) > 0 {
		b.WriteString("  datadog-agent:\n")
		if agent.Image != "" {
			fmt.Fprintf(&b, "    image: %q\n", agent.Image)
		}
		if agent.Pull != "" {
			fmt.Fprintf(&b, "    pull_policy: %s\n", agent.Pull)
		}
		if len(env) > 0 {
			b.WriteString("    environment:\n")
			for _, k := range sortedStringKeys(env) {
				fmt.Fprintf(&b, "      %s: %q\n", k, env[k])
			}
		}
	}
	var enabled []string
	for _, n := range sortedGenNames(p) {
		spec := p.Generators[n]
		if e, ok := spec["enabled"]; ok && !truthy(e) {
			continue
		}
		enabled = append(enabled, n)
		genEnv := map[string]string{}
		for k, v := range spec {
			if k == "enabled" || k == "scale" {
				continue
			}
			genEnv[envKey(k)] = yamlScalar(v)
		}
		if len(genEnv) == 0 {
			continue
		}
		fmt.Fprintf(&b, "  %s:\n    environment:\n", n)
		for _, k := range sortedStringKeys(genEnv) {
			fmt.Fprintf(&b, "      %s: %q\n", k, genEnv[k])
		}
	}
	return b.String(), enabled
}

func truthy(v any) bool {
	switch x := v.(type) {
	case bool:
		return x
	case string:
		return x == "true" || x == "yes" || x == "1"
	}
	return true
}

func sortedStringKeys(m map[string]string) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return ks
}

// compose wraps `docker compose [-p project] -f … ` invocations.
type compose struct {
	cmd     []string
	project string // -p; "" keeps the compose file's own name
	files   []string
	env     []string
	dir     string
	log     func(string, ...any)
}

func (c *compose) args(extra ...string) []string {
	var a []string
	a = append(a, c.cmd[1:]...)
	if c.project != "" {
		a = append(a, "-p", c.project)
	}
	for _, f := range c.files {
		a = append(a, "-f", f)
	}
	return append(a, extra...)
}

func (c *compose) run(ctx context.Context, extra ...string) error {
	cmd := exec.CommandContext(ctx, c.cmd[0], c.args(extra...)...)
	cmd.Dir = c.dir
	cmd.Env = append(os.Environ(), c.env...)
	cmd.Stdout, cmd.Stderr = os.Stderr, os.Stderr
	c.log("$ %s %s", c.cmd[0], strings.Join(c.args(extra...), " "))
	return cmd.Run()
}

func (c *compose) output(ctx context.Context, extra ...string) ([]byte, error) {
	cmd := exec.CommandContext(ctx, c.cmd[0], c.args(extra...)...)
	cmd.Dir = c.dir
	cmd.Env = append(os.Environ(), c.env...)
	var out, errb bytes.Buffer
	cmd.Stdout, cmd.Stderr = &out, &errb
	err := cmd.Run()
	if err != nil {
		return out.Bytes(), fmt.Errorf("%v: %s", err, strings.TrimSpace(errb.String()))
	}
	return out.Bytes(), nil
}

func runProfiles(args []string) int {
	dir := "profiles"
	if len(args) > 0 && args[0] != "-h" && args[0] != "--help" {
		dir = args[0]
	}
	matches, _ := filepath.Glob(filepath.Join(dir, "*.yaml"))
	if len(matches) == 0 {
		return fail("no profiles in %s (run from the repo root, or pass a directory)", dir)
	}
	fmt.Printf("\nProfiles in %s (aoc run --profile PATH):\n\n", dir)
	for _, m := range matches {
		p, err := loadProfile(m)
		if err != nil {
			fmt.Printf("  %-28s (invalid: %v)\n", m, err)
			continue
		}
		fmt.Printf("  %-28s %s\n", m, wrap(p.Description, 90, 31))
		fmt.Printf("  %-28s duration=%s warmup=%s drain=%s generators=%s faults=%d\n\n", "", p.Duration, p.Warmup, p.Drain, strings.Join(p.enabledGenerators(), ","), len(p.Faults))
	}
	return 0
}

func sortedGenNames(p *Profile) []string {
	names := make([]string, 0, len(p.Generators))
	for n := range p.Generators {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

func wrap(s string, width, indent int) string {
	words := strings.Fields(s)
	var lines []string
	var cur string
	for _, w := range words {
		if len(cur)+len(w)+1 > width && cur != "" {
			lines = append(lines, cur)
			cur = w
			continue
		}
		if cur == "" {
			cur = w
		} else {
			cur += " " + w
		}
	}
	if cur != "" {
		lines = append(lines, cur)
	}
	return strings.Join(lines, "\n"+strings.Repeat(" ", indent))
}

// runSpec is one measured run. `aoc run` builds it from flags; `aoc ab`
// builds one per agent.
type runSpec struct {
	profile     *Profile
	profileSrc  []byte // the profile as written, copied into the results dir
	name        string
	agent       agentSpec
	resultsDir  string
	composeCmd  string
	composeFile string
	intake      string
	keep        bool
	noBuild     bool
	tags        []string // extra tags on the intake's aoc.* metrics and the agent's DD_TAGS
	logf        func(string, ...any)
	// stack names this run's compose project and its containers
	// (<stack>-intake, <stack>-agent, <stack>-gen-*); with ports, it lets
	// several runs share a host. Empty: the compose file's own name, aoc.
	stack      string
	intakePort int // host port for the intake's HTTP (0: the compose default)
	tcpPort    int // host port for the intake's TCP (0: the compose default)
}

// stackName is the prefix of this run's container names.
func (s runSpec) stackName() string {
	if s.stack == "" {
		return "aoc"
	}
	return s.stack
}

var errInterrupted = errors.New("interrupted")

// executeRun brings the stack up, measures one window, writes the results
// directory and (unless keep) tears the stack down. It returns the report,
// or errInterrupted when the context was cancelled.
func executeRun(ctx context.Context, s runSpec) (*report.Report, error) {
	p := s.profile
	name := sanitize(s.name)
	logf := s.logf
	if err := os.MkdirAll(s.resultsDir, 0o755); err != nil {
		return nil, err
	}
	override, enabled := overrideCompose(p, s.agent)
	if len(enabled) == 0 {
		return nil, errors.New("profile enables no generators")
	}
	overridePath := filepath.Join(s.resultsDir, "compose.override.yml")
	if err := os.WriteFile(overridePath, []byte(override), 0o644); err != nil {
		return nil, err
	}
	if len(s.profileSrc) > 0 {
		os.WriteFile(filepath.Join(s.resultsDir, "profile.yaml"), s.profileSrc, 0o644)
	}

	c := &compose{cmd: strings.Fields(s.composeCmd), project: s.stack, files: append([]string{s.composeFile}, p.Compose...), dir: ".", log: logf}
	c.files = append(c.files, overridePath)
	c.env = []string{"AOC_RUN_NAME=" + name, "AOC_STACK=" + s.stackName()}
	if s.intakePort > 0 {
		c.env = append(c.env, fmt.Sprintf("AOC_INTAKE_PORT=%d", s.intakePort))
	}
	if s.tcpPort > 0 {
		c.env = append(c.env, fmt.Sprintf("AOC_TCP_PORT=%d", s.tcpPort))
	}
	if s.agent.Image != "" {
		c.env = append(c.env, "DD_AGENT_IMAGE="+s.agent.Image)
	}
	if len(s.tags) > 0 {
		// The compose files add harness:aoc and run:<name> themselves.
		c.env = append(c.env, "AOC_DD_TAGS=harness:aoc,"+strings.Join(s.tags, ","), "DD_TAGS="+strings.Join(s.tags, " "))
	}
	down := func() { c.run(context.Background(), "down", "-v", "--remove-orphans") }
	stop := func() (*report.Report, error) {
		if !s.keep {
			down()
		}
		return nil, errInterrupted
	}

	// Clean slate: old log files/offsets would pollute the ledgers.
	c.run(ctx, "down", "-v", "--remove-orphans")
	upArgs := []string{"up", "-d"}
	if !s.noBuild {
		upArgs = append(upArgs, "--build")
	}
	if err := c.run(ctx, append(upArgs, "intake", "datadog-agent")...); err != nil {
		if ctx.Err() != nil {
			return stop()
		}
		return nil, fmt.Errorf("compose up: %w", err)
	}
	if err := waitHTTP(ctx, s.intake+"/healthz", 60*time.Second); err != nil {
		if ctx.Err() != nil {
			return stop()
		}
		return nil, fmt.Errorf("intake not reachable at %s: %w", s.intake, err)
	}
	logf("intake is up at %s", s.intake)
	if err := waitAgent(ctx, c, 180*time.Second, logf); err != nil {
		if ctx.Err() != nil {
			return stop()
		}
		return nil, err
	}
	imageID, digest := imageIdentity(ctx, s.stackName()+"-agent", s.agent.Image)
	if digest != "" {
		logf("agent image %s = %s", s.agent.Image, digest)
	}

	if err := c.run(ctx, append([]string{"up", "-d", "--no-build"}, enabled...)...); err != nil {
		if ctx.Err() != nil {
			return stop()
		}
		return nil, fmt.Errorf("compose up generators: %w", err)
	}
	logf("generators started: %s", strings.Join(enabled, ", "))
	if err := waitGenerators(ctx, s.intake, len(enabled), 60*time.Second, logf); err != nil {
		logf("warning: %v", err)
	}
	if p.Warmup > 0 {
		logf("warm-up %s", p.Warmup)
		if !sleepCtx(ctx, p.Warmup.D()) {
			return stop()
		}
	}

	// Open the measured window.
	if _, err := http.Post(s.intake+"/harness/reset?name="+name, "", nil); err != nil {
		return nil, fmt.Errorf("reset: %w", err)
	}
	windowStart := time.Now()
	logf("measured window open for %s (metrics tagged run:%s)", p.Duration, name)

	// Fault timeline, cut off at the end of the window.
	windowCtx, cancelWindow := context.WithDeadline(ctx, windowStart.Add(p.Duration.D()))
	defer cancelWindow()
	faultsDone := make(chan struct{})
	go func() {
		defer close(faultsDone)
		steps := append([]FaultStep(nil), p.Faults...)
		sort.SliceStable(steps, func(i, j int) bool { return steps[i].At < steps[j].At })
		for _, st := range steps {
			if st.At.D() >= p.Duration.D() {
				logf("fault step at t+%s is beyond the %s window; skipped", st.At, p.Duration)
				continue
			}
			if !sleepCtx(windowCtx, time.Until(windowStart.Add(st.At.D()))) {
				return
			}
			if st.Clear {
				req, _ := http.NewRequest("DELETE", s.intake+"/harness/faults", nil)
				if resp, err := http.DefaultClient.Do(req); err == nil {
					resp.Body.Close()
					logf("faults cleared (t+%s)", st.At)
				}
				continue
			}
			body, _ := json.Marshal(st.Set)
			if resp, err := http.Post(s.intake+"/harness/faults", "application/json", bytes.NewReader(body)); err == nil {
				resp.Body.Close()
				logf("faults set (t+%s): %s", st.At, string(body))
			}
		}
	}()

	if !sleepCtx(ctx, time.Until(windowStart.Add(p.Duration.D()))) {
		return stop()
	}
	<-faultsDone
	// Make sure no fault outlives the window, so the drain is clean.
	if req, err := http.NewRequest("DELETE", s.intake+"/harness/faults", nil); err == nil {
		if resp, err := http.DefaultClient.Do(req); err == nil {
			resp.Body.Close()
		}
	}

	logf("window closed — stopping generators")
	mark(s.intake, "measurement window closed")
	c.run(ctx, append([]string{"stop"}, enabled...)...)
	mark(s.intake, "generators stopped, draining")
	hadFaults := len(p.Faults) > 0
	if hadFaults {
		logf("draining for the full %s (faults were injected: the agent's retry backoff can be long)", p.Drain)
	} else {
		logf("draining for up to %s (until everything arrived or the intake goes quiet)", p.Drain)
	}
	drainUntilQuiet(ctx, s.intake, p.Drain.D(), hadFaults, logf)
	mark(s.intake, "drain finished")
	if ctx.Err() != nil {
		return stop()
	}

	// Collect.
	r, err := fetchReportFor(s.intake, name)
	if err != nil {
		return nil, err
	}
	r.Agent.ImageID, r.Agent.Digest = imageID, digest
	if hadFaults && r.Delivery.Missing > 0 {
		r.Notes = append(r.Notes, fmt.Sprintf("%s records were still missing when the %s drain ended. Faults were injected during the window and the agent retries with exponential backoff (up to minutes), so these may still have been buffered in the agent rather than lost; use a longer `drain` to tell the two apart.", fmtInt(r.Delivery.Missing), p.Drain))
	}
	// The agent's own profiles: the intake kept a copy of every upload
	// (and forwarded it to Datadog). The period that covers the end of the
	// window is uploaded up to a period later, so give it a moment.
	waitProfiles(ctx, s.intake, r.WindowEnd, 75*time.Second, logf)
	caps, pst, perr := collectProfiles(s.intake, s.resultsDir, r.WindowStart, r.WindowEnd)
	switch {
	case perr != nil:
		logf("profiles: %v", perr)
	case len(caps) == 0 && pst.Received == 0:
		logf("profiles: none uploaded (DD_INTERNAL_PROFILING_ENABLED and DD_APM_ENABLED must be true, and apm_config.profiling_dd_url must point at the intake)")
	default:
		r.Profiles = prof.Summaries(caps, 40)
		// The profiler tags the build it runs in: the exact commit behind
		// each side, for the code section of the brief.
		r.Agent.Commit, r.Agent.Repo = profileTag(caps, "git.commit.sha"), profileTag(caps, "git.repository_url")
		note := ""
		if pst.ForwardErrors > 0 {
			note = fmt.Sprintf("; %d forward error(s), last: %s", pst.ForwardErrors, pst.LastError)
		}
		logf("profiles: %d upload(s) over the window saved under profiles/ (%d view(s))%s", len(caps), len(r.Profiles), note)
	}
	if outb, err := c.output(ctx, "logs", "--no-color", "--no-log-prefix", "--tail", "20000", "datadog-agent"); err == nil {
		os.WriteFile(filepath.Join(s.resultsDir, "agent.log"), outb, 0o644)
		r.AgentLog = summarizeAgentLog(outb, 20000)
	}
	raw, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return nil, err
	}
	csv, _ := fetchTimeseriesCSV(s.intake, r.WindowStart.Unix())
	if err := writeReportFiles(s.resultsDir, r, raw, csv); err != nil {
		return nil, err
	}
	if outb, err := c.output(ctx, "exec", "-T", "datadog-agent", "agent", "status"); err == nil {
		os.WriteFile(filepath.Join(s.resultsDir, "agent-status.txt"), outb, 0o644)
	} else {
		logf("agent status unavailable: %v", err)
	}
	if outb, err := c.output(ctx, "logs", "--no-color", "--tail", "2000", "intake"); err == nil {
		os.WriteFile(filepath.Join(s.resultsDir, "intake.log"), outb, 0o644)
	}
	for _, g := range enabled {
		if outb, err := c.output(ctx, "logs", "--no-color", "--no-log-prefix", "--tail", "500", g); err == nil {
			os.WriteFile(filepath.Join(s.resultsDir, g+".log"), outb, 0o644)
		}
	}

	if !s.keep {
		down()
	} else {
		logf("stack left running (--keep); intake at %s", s.intake)
	}
	return r, nil
}

// imageIdentity resolves what the agent container actually runs: the docker
// image ID and, for a pulled image, the registry digest (repo@sha256:…) —
// the exact answer to "which build was `latest` at the time". Best effort.
func imageIdentity(ctx context.Context, container, image string) (id, digest string) {
	out, err := exec.CommandContext(ctx, "docker", "inspect", "--format", "{{.Image}}", container).Output()
	if err != nil {
		return "", ""
	}
	id = strings.TrimSpace(string(out))
	out, err = exec.CommandContext(ctx, "docker", "image", "inspect", "--format", `{{join .RepoDigests " "}}`, id).Output()
	if err != nil {
		return id, ""
	}
	repo := image
	if i := strings.LastIndex(repo, ":"); i > strings.LastIndex(repo, "/") {
		repo = repo[:i]
	}
	digests := strings.Fields(string(out))
	for _, d := range digests {
		if strings.HasPrefix(d, repo+"@") {
			return id, d
		}
	}
	if len(digests) > 0 {
		return id, digests[0]
	}
	return id, ""
}

func newLogf() func(string, ...any) {
	return newLogfPrefix("")
}

// newLogfPrefix is newLogf with a tag after the time, for runs that log
// alongside each other.
func newLogfPrefix(prefix string) func(string, ...any) {
	if prefix != "" {
		prefix = "[" + prefix + "]  "
	}
	return func(format string, a ...any) {
		fmt.Fprintf(os.Stderr, "  %s  %s%s\n", time.Now().Format("15:04:05"), prefix, fmt.Sprintf(format, a...))
	}
}

func runRun(args []string) int {
	fs := newFlagSet("run",
		"Run one experiment end to end with docker compose: start the intake and\n"+
			"the agent, wait for the agent to be healthy, start the generators, open\n"+
			"a measured window after a warm-up, apply the profile's fault timeline,\n"+
			"stop the generators, drain, then write report.json/report.md/timeseries.csv\n"+
			"plus the agent's status and logs into the results directory.\n"+
			"To test two agent images against each other, see `aoc ab`.",
		"  aoc run --profile profiles/baseline.yaml --name baseline\n"+
			"  aoc run --profile profiles/baseline.yaml --fault latency_ms=500,jitter_ms=200 --name slow-intake\n"+
			"  aoc run --profile profiles/baseline.yaml --agent-image datadog/agent-dev:my-build --name candidate\n"+
			"  aoc compare results/baseline results/candidate")
	profilePath := fs.Str("profile", "", "experiment profile (YAML), see profiles/README.md")
	name := fs.Str("name", "", "run name → results/<name> (default: profile name)")
	agentImage := fs.Str("agent-image", "", "agent image under test (overrides the profile and DD_AGENT_IMAGE)")
	pull := fs.Str("pull", "", "pull policy for the agent image: always | missing | never (default: compose's, missing)")
	duration := fs.Duration("duration", 0, "override the profile's measured window")
	composeFile := fs.Str("compose-file", "docker-compose.yml", "base compose file")
	composeCmd := fs.Str("compose-cmd", "docker compose", "compose command")
	intake := fs.Str("intake", "http://localhost:8282", "how this machine reaches the intake")
	out := fs.Str("out", "results", "results root directory")
	keep := fs.Bool("keep", false, "leave the stack running afterwards (default: docker compose down -v)")
	noBuild := fs.Bool("no-build", false, "do not rebuild the aoc image")
	mkNotebook := fs.Bool("notebook", os.Getenv("DD_APP_KEY") != "", "create a Datadog notebook for the run (default: when DD_APP_KEY is set; notebook.json is always written)")
	ddSite := fs.Str("dd-site", envOr("DD_SITE", "datadoghq.com"), "Datadog site for the notebook (env DD_SITE)")
	fault := fs.list("fault", true, "an intake fault for the whole window, e.g. latency_ms=300 or drop_rate=0.05; replaces the profile's fault timeline; repeatable, commas allowed")
	if !fs.parse(args) {
		return 2
	}
	if *profilePath == "" {
		return fail("run: --profile is required (see aoc profiles)")
	}
	if err := checkPull(*pull); err != nil {
		return fail("run: --pull: %v", err)
	}
	p, err := loadProfile(*profilePath)
	if err != nil {
		return fail("run: %v", err)
	}
	if *name == "" {
		*name = p.Name
	}
	if *duration > 0 {
		p.Duration = gen.Duration(*duration)
	}
	faults, err := parseFaults(fault.vals)
	if err != nil {
		return fail("run: --fault: %v", err)
	}
	if faults != nil {
		p.Faults = []FaultStep{{Set: faults}}
	}
	img := *agentImage
	if img == "" {
		img = p.Agent.Image
	}
	if img == "" {
		img = os.Getenv("DD_AGENT_IMAGE")
	}
	src, _ := os.ReadFile(*profilePath)
	spec := runSpec{
		profile: p, profileSrc: src, name: *name,
		agent:      agentSpec{Image: img, Pull: *pull},
		resultsDir: filepath.Join(*out, sanitize(*name)),
		composeCmd: *composeCmd, composeFile: *composeFile, intake: *intake,
		keep: *keep, noBuild: *noBuild, logf: newLogf(),
	}

	ctx, cancel := signalContext()
	defer cancel()
	fmt.Fprintf(os.Stderr, "\naoc run  %s  profile=%s  agent=%s  window=%s  warmup=%s  drain=%s\n  %s\n\n",
		*name, *profilePath, orDefault(img, "compose default"), p.Duration, p.Warmup, p.Drain, p.Description)
	r, err := executeRun(ctx, spec)
	if errors.Is(err, errInterrupted) {
		fmt.Fprintln(os.Stderr, "\naoc: interrupted")
		return 130
	}
	if err != nil {
		return fail("run: %v", err)
	}
	nbRes, nbErr := makeNotebook(context.Background(), []*report.Report{r}, notebook.Options{Site: *ddSite, AppURL: ddapi.AppURLFromEnv()}, filepath.Join(spec.resultsDir, "notebook.json"), ddapi.FromEnv(), !*mkNotebook)
	fmt.Fprintf(os.Stderr, "\nresults in %s (report.md, report.json, timeseries.csv, notebook.json, agent-status.txt, agent.log)\n\n", spec.resultsDir)
	printVerdict(r)
	switch {
	case nbErr != nil:
		fmt.Fprintf(os.Stderr, "notebook: %v\n", nbErr)
	case nbRes.URL != "":
		fmt.Printf("notebook: %s\n", nbRes.URL)
	case *mkNotebook:
		fmt.Printf("notebook: DD_APP_KEY not set — wrote %s; create it with `aoc notebook --results %s` or the Datadog MCP\n", nbRes.File, spec.resultsDir)
	}
	if r.Delivery.Missing > 0 || r.Delivery.Duplicates > 0 {
		return 3
	}
	return 0
}

// checkPull validates a compose pull_policy value.
func checkPull(p string) error {
	switch p {
	case "", "always", "missing", "never":
		return nil
	}
	return fmt.Errorf("%q is not one of always, missing, never", p)
}

// mark posts an annotation event through the intake (a no-op without Datadog).
func mark(intake, text string) {
	if resp, err := http.Post(intake+"/harness/mark?text="+url.QueryEscape(text), "", nil); err == nil {
		resp.Body.Close()
	}
}

func orDefault(s, d string) string {
	if s == "" {
		return d
	}
	return s
}

func sleepCtx(ctx context.Context, d time.Duration) bool {
	if d <= 0 {
		return ctx.Err() == nil
	}
	select {
	case <-ctx.Done():
		return false
	case <-time.After(d):
		return true
	}
}

func waitHTTP(ctx context.Context, url string, timeout time.Duration) error {
	deadline := time.Now().Add(timeout)
	client := &http.Client{Timeout: 2 * time.Second}
	for {
		resp, err := client.Get(url)
		if err == nil {
			resp.Body.Close()
			if resp.StatusCode < 400 {
				return nil
			}
		}
		if time.Now().After(deadline) {
			if err == nil {
				return fmt.Errorf("HTTP %d", resp.StatusCode)
			}
			return err
		}
		if !sleepCtx(ctx, time.Second) {
			return ctx.Err()
		}
	}
}

// waitAgent polls `agent health` inside the container.
func waitAgent(ctx context.Context, c *compose, timeout time.Duration, logf func(string, ...any)) error {
	deadline := time.Now().Add(timeout)
	logf("waiting for the agent to report healthy")
	var lastErr error
	for time.Now().Before(deadline) {
		out, err := c.output(ctx, "exec", "-T", "datadog-agent", "agent", "health")
		if err == nil {
			logf("agent healthy")
			return nil
		}
		lastErr = fmt.Errorf("%v %s", err, strings.TrimSpace(string(out)))
		if !sleepCtx(ctx, 3*time.Second) {
			return ctx.Err()
		}
	}
	return fmt.Errorf("agent did not become healthy within %s: %v", timeout, lastErr)
}

type intakeStatus struct {
	Generators []struct {
		Name  string `json:"name"`
		Final bool   `json:"final"`
	} `json:"generators"`
	RecentLogsPerSec float64 `json:"recent_logs_per_sec"`
	Missing          int64   `json:"missing"`
}

func getStats(url string) (*intakeStatus, error) {
	resp, err := (&http.Client{Timeout: 10 * time.Second}).Get(url + "/harness/status")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	var s intakeStatus
	if err := json.NewDecoder(resp.Body).Decode(&s); err != nil {
		return nil, err
	}
	return &s, nil
}

func waitGenerators(ctx context.Context, url string, n int, timeout time.Duration, logf func(string, ...any)) error {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		if s, err := getStats(url); err == nil && len(s.Generators) >= n {
			logf("%d generator(s) reporting to the intake", len(s.Generators))
			return nil
		}
		if !sleepCtx(ctx, time.Second) {
			return ctx.Err()
		}
	}
	return fmt.Errorf("only some generators registered within %s — check `docker compose logs gen-plain`", timeout)
}

// drainUntilQuiet waits for every generator's final report and for missing
// to reach zero, bounded by max. Without faults it also stops once the
// intake has been quiet for 10 s; after faults the agent may be sleeping in
// its retry backoff, so only the full drain counts.
func drainUntilQuiet(ctx context.Context, url string, max time.Duration, hadFaults bool, logf func(string, ...any)) {
	deadline := time.Now().Add(max)
	quiet := 0
	for time.Now().Before(deadline) {
		if !sleepCtx(ctx, time.Second) {
			return
		}
		s, err := getStats(url)
		if err != nil {
			continue
		}
		allFinal := len(s.Generators) > 0
		for _, g := range s.Generators {
			if !g.Final {
				allFinal = false
			}
		}
		if allFinal && s.Missing == 0 {
			logf("drained: everything delivered")
			return
		}
		if s.RecentLogsPerSec == 0 {
			quiet++
		} else {
			quiet = 0
		}
		if allFinal && quiet >= 10 && !hadFaults {
			logf("drained: intake quiet for 10 s, %d record(s) still missing", s.Missing)
			return
		}
	}
	logf("drain ended after %s", max)
}
